[project]
authors = ["Bror Jonsson <brorfred@gmail.com>"]
channels = ["conda-forge", "rapidsai", "conda-forge", "nvidia"]
description = "Add a short description here"
name = "pixi-forest"
platforms = ["linux-64"]
version = "0.1.0"
channel-priority = "disabled"

[tasks]

[dependencies]
python = "3.12.*"
cuda-version = "12.5.*"
rapids = "24.10.0.*"
numpy = ">=2.0.2,<3"
matplotlib = ">=3.9.4,<4"
scikit-learn = "==1.5"
cartopy = ">=0.24.0,<0.25"
xgboost = ">=2.1.1,<3"
shap = ">=0.46.0,<0.47"
quantile-forest = ">=1.3.11,<2"
ipython = ">=8.30.0,<9"
optuna = ">=3.6.1,<4"
jupyter = ">=1.1.1,<2"
notebook = ">=7.3.1,<8"
jupyterlab = ">=4.3.3,<5"
optuna-integration = ">=4.1.0,<5"
pyresample = ">=1.31.0,<2"
interpret = ">=0.6.8,<0.7"

[pypi-dependencies]
ocean-forest = { git = "https://github.com/brorfred/ocean_forest.git" }
njord = { path = "/home/bror/code/njord", editable = true }
projmap = { path = "/home/bror/code/projmap", editable = true }

